# Generated by Django 5.1.3 on 2024-12-30 20:23

import django.db.models.deletion
import taxi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_historicalcar_historicalconsumer_historicaldriver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'Пассажир', 'verbose_name_plural': 'Пассажиры'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='historicalconsumer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Пассажир', 'verbose_name_plural': 'historical Пассажиры'},
        ),
        migrations.AlterModelOptions(
            name='historicaldriver',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Водитель', 'verbose_name_plural': 'historical Водители'},
        ),
        migrations.AlterModelOptions(
            name='historicalrideaddressesqueue',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ride addresses queue', 'verbose_name_plural': 'historical Очереди поездок'},
        ),
        migrations.AlterModelOptions(
            name='rideaddressesqueue',
            options={'ordering': ['order', 'date_ended', 'date_created'], 'verbose_name_plural': 'Очереди поездок'},
        ),
        migrations.AddField(
            model_name='consumer',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=taxi.models.get_user_directory_path, verbose_name='Profile image'),
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=taxi.models.get_user_directory_path, verbose_name='Profile image'),
        ),
        migrations.AddField(
            model_name='historicalconsumer',
            name='profile_image',
            field=models.TextField(max_length=100, null=True, verbose_name='Profile image'),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='profile_image',
            field=models.TextField(max_length=100, null=True, verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='rideaddressesqueue',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='taxi.ride'),
        ),
    ]
