# Generated by Django 5.1.3 on 2024-12-26 19:55

import taxi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_historicalcar_historicalconsumer_historicaldriver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldriver',
            name='current_car',
        ),
        migrations.RemoveField(
            model_name='historicaldriver',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldriver',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicaldriver',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'Пассажир', 'verbose_name_plural': 'Пассажиры'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='historicalrideaddressesqueue',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ride addresses queue', 'verbose_name_plural': 'historical Очереди поездок'},
        ),
        migrations.AlterModelOptions(
            name='rideaddressesqueue',
            options={'ordering': ['order', 'date_ended', 'date_created'], 'verbose_name_plural': 'Очереди поездок'},
        ),
        migrations.AddField(
            model_name='consumer',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=taxi.models.get_user_directory_path, verbose_name='Profile image'),
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=taxi.models.get_user_directory_path, verbose_name='Profile image'),
        ),
        migrations.DeleteModel(
            name='HistoricalConsumer',
        ),
        migrations.DeleteModel(
            name='HistoricalDriver',
        ),
    ]
