# Generated by Django 5.1.3 on 2024-12-12 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['street', 'name'], 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name_plural': 'Пассажиры'},
        ),
        migrations.AlterModelOptions(
            name='consumerrate',
            options={'verbose_name_plural': 'Оценки пассажиров'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['city', 'name'], 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='driverrate',
            options={'verbose_name_plural': 'Оценки водителей'},
        ),
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['driver', 'date_created'], 'verbose_name_plural': 'Поездки'},
        ),
        migrations.AlterModelOptions(
            name='rideaddressesqueue',
            options={'ordering': ['order', 'date_ended', 'date_created'], 'verbose_name_plural': 'Истории путей'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'ordering': ['district', 'name'], 'verbose_name_plural': 'Улицы'},
        ),
        migrations.AddField(
            model_name='consumer',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='taxi.district'),
        ),
        migrations.AlterField(
            model_name='consumerrate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='driverrate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rideaddressesqueue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
