# Generated by Django 5.1.3 on 2025-01-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_alter_ride_options_ride_addresses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerrate',
            name='author',
        ),
        migrations.RemoveField(
            model_name='consumerrate',
            name='target',
        ),
        migrations.RemoveField(
            model_name='driverrate',
            name='author',
        ),
        migrations.RemoveField(
            model_name='driverrate',
            name='target',
        ),
    ]
